# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='desc',
            field=models.CharField(max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.CharField(max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='desc',
            field=models.CharField(max_length=256, verbose_name='description'),
        ),
    ]
