# Generated by Django 2.0.3 on 2018-04-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='accounts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='accountbalancecache',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='balance_caches',
                to='expenses.Account',
            ),
        ),
        migrations.AlterField(
            model_name='accountsyncevent',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sync_events',
                to='expenses.Account',
            ),
        ),
        migrations.AlterField(
            model_name='accountsyncevent',
            name='subtransaction',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sync_event',
                to='expenses.Subtransaction',
            ),
        ),
        migrations.AlterField(
            model_name='subtransaction',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subtransactions',
                to='expenses.Account',
            ),
        ),
        migrations.AlterField(
            model_name='subtransaction',
            name='transaction',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subtransactions',
                to='expenses.Transaction',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transaction_tags',
                to='expenses.Tag',
            ),
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='transaction',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transaction_tags',
                to='expenses.Transaction',
            ),
        ),
    ]
