# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20161106_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='priority',
        ),
    ]
