# Generated by Django 2.0.3 on 2018-04-30 09:29

from django.db import migrations
from expenses.models import *

def update_subtransaction_amount(apps, schema_editor):
    Subtransaction = apps.get_model('expenses', 'subtransaction')
    for sub in Subtransaction.objects.all():
        sub.amount *= 100
        sub.save()

def update_account_balance_cache_balance(apps, schema_editor):
    AccountBalanceCache = apps.get_model('expenses', 'accountbalancecache')
    for cache in AccountBalanceCache.objects.all():
        cache.balance *= 100
        cache.save()

def update_account_sync_event(apps, schema_editor):
    AccountSyncEvent = apps.get_model('expenses', 'accountsyncevent')
    for event in AccountSyncEvent.objects.all():
        event.balance *= 100
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20180428_1815'),
    ]

    operations = [
        migrations.RunPython(update_subtransaction_amount),
        migrations.RunPython(update_account_balance_cache_balance),
        migrations.RunPython(update_account_sync_event),
    ]
