# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_preset_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='transaction_desc',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
