# Generated by Django 2.0.3 on 2018-04-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0003_auto_20180430_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetsubtransaction',
            name='preset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='preset_subtransactions',
                to='expenses.Preset',
            ),
        ),
        migrations.AlterField(
            model_name='presettransactiontag',
            name='preset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='preset_tags',
                to='expenses.Preset',
            ),
        ),
    ]
