# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20161202_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountamountcache',
            old_name='balance',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='accountsyncevent',
            old_name='balance',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='chainedsubtransactionignored',
            old_name='chained_balance',
            new_name='chained_account',
        ),
        migrations.RenameField(
            model_name='chainedsubtransactionpendingnew',
            old_name='chained_balance',
            new_name='chained_account',
        ),
        migrations.RenameField(
            model_name='presetsubtransaction',
            old_name='balance',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='subtransaction',
            old_name='balance',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='chainedaccount',
            old_name='master_balance',
            new_name='master_account',
        ),
		migrations.RenameField(
            model_name='chainedaccount',
            old_name='slave_balance',
            new_name='slave_account',
        ),
    ]
