# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20161202_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='desc',
            field=models.CharField(blank=True, max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='chainedaccount',
            name='master_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_account', to='expenses.Account'),
        ),
        migrations.AlterField(
            model_name='chainedaccount',
            name='slave_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_account', to='expenses.Account'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='desc',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='preset',
            name='transaction_desc',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.CharField(blank=True, max_length=256, verbose_name='description'),
        ),
    ]
