# Generated by Django 5.0.6 on 2024-09-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0004_auto_20180430_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalancecache',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
