# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20161202_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountAmountCache',
            new_name='AccountBalanceCache',
        ),
    ]
