# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20161202_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalancecache',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='accountsyncevent',
            old_name='amount',
            new_name='balance',
        ),
    ]
