# Generated by Django 5.0.6 on 2025-05-05 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0008_accountbalancecache_timezone_offset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionImage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('image', models.BinaryField()),
                ('header', models.CharField(max_length=100)),
                (
                    'transaction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transaction_images',
                        to='expenses.transaction',
                    ),
                ),
            ],
        ),
    ]
