# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0009_auto_20161202_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainedAccountRequestPendingNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='description')),
                ('relation', models.IntegerField(default=0)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='friendrelation',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendrelation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRelation',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
