# Generated by Django 5.0.6 on 2025-06-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_transactionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionimage',
            name='header',
        ),
        migrations.AlterField(
            model_name='transactionimage',
            name='image',
            field=models.ImageField(upload_to='transactions'),
        ),
    ]
